version: '3.1'

services:
  cqrs-demo:
    image: cqrs-demo
    restart: always
    ports:
      - "3030:3030"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './db:/docker-entrypoint-initdb.d'